admin/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    login, logout,
    password_reset, password_reset_done,
    password_reset_confirm, password_reset_complete
)
from apps.users import views

url_password_reset = {
    'template_name':'auth/password/send_email.html',
    'email_template_name':'auth/password/reset_email.html'
}
url_password_done = {
    'template_name':'auth/password/reset_done.html'
}
url_password_confirm = {
    'template_name': 'auth/password/reset_confirm.html'
}
url_done = {
    'template_name': 'auth/password/reset_complete.html'
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login, {'template_name':'auth/login.html'}, name='login'),
    url(r'^register/', views.register_user, name = 'register'),
    url(r'^logout/$', logout, {'next_page': '/'}, name= 'logout'),
    url(r'^reset/password/$', password_reset,
        url_password_reset, name='password_reset'
    ),
    url(r'^reset/password_done/$', password_reset_done,
        url_password_done, name='password_reset_done'
    ),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        url_password_confirm, name='password_reset_confirm'
    ),
    url(r'^reset/done', password_reset_complete,
        url_done, name='password_reset_complete'
    ),
    #urls admin
    url(r'^', include('apps.home.urls')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^teams/', include('apps.teams.urls', namespace='teams')),
    url(r'^players/', include('apps.players.urls', namespace='players')),
    url(r'^competitions/', include('apps.competitions.urls', namespace='competitions')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/players/urls.py
from django.conf.urls import url
from apps.players import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^list/', login_required(views.ListPlayer.as_view()), name = 'list'),
    url(r'^create/', login_required(views.CreatePlayer.as_view()), name = 'create'),
    url(r'^edit/(?P<pk>\w+)/$', login_required(views.EditPlayer.as_view()), name = 'edit'),
    url(r'^delete/(?P<pk>\w+)/$', login_required(views.DeletePlayer.as_view()), name = 'delete'),
    url(r'^report_player/(?P<pk>\w+)/$', views.report_player, name = 'report_player'),
    url(r'^test_report/', views.test_report, name = 'test_report'),
]

apps/teams/urls.py
from django.conf.urls import url
from apps.teams import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^list/', login_required(views.ListTeams.as_view()), name = 'list'),
    url(r'^create/', login_required(views.CreateTeam.as_view()), name = 'create'),
    url(r'^edit/(?P<pk>\w+)/$', login_required(views.EditTeam.as_view()), name = 'edit'),
    url(r'^delete/(?P<pk>\w+)/$', login_required(views.DeleteTeam.as_view()), name = 'delete'),
    url(r'^players/(?P<pk>\w+)/$', login_required(views.ListPlayersByTeam.as_view()), name = 'players'),
    url(r'^stadium/(?P<pk>\w+)/$', login_required(views.ListStadiumByTeam.as_view()), name = 'stadium'),
    url(r'^get_players_by_country/$', views.get_players_by_country, name = 'get_players_by_country'),
    url(r'^get_detail_player/$', views.get_detail_player, name = 'get_detail_player'),
]

apps/players/models.py
from django.db import models
from apps.teams.models import Team
from django_countries.fields import CountryField

# Create your models here.


class Player(models.Model):
    name = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    number = models.IntegerField()
    position = models.CharField(max_length=100)
    team = models.ForeignKey(
        Team,
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='player_image', blank=True)
    country = CountryField(blank_label='select country', null=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Statistics(models.Model):
    pace = models.IntegerField()
    shooting = models.IntegerField()
    passing = models.IntegerField()
    dribbling = models.IntegerField()
    defending = models.IntegerField()
    physical = models.IntegerField()
    player = models.OneToOneField(Player, related_name='statistic')

apps/players/forms.py
from django import forms
from apps.players.models import Player, Statistics
from django_countries.widgets import CountrySelectWidget


class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = (
            'name',
            'lastname',
            'number',
            'position',
            'team',
            'image',
            'country',)

        labels = {
            'name': 'Name',
            'lastname': 'Lastname',
            'number': 'Number',
            'position': 'Position',
            'team': 'Team',
            'image': 'Image',
            'country': 'Country',
        }

        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': False
                }
            ),
            'lastname': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'number': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'position': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'team': forms.Select(
                attrs={
                    'class': 'form-control'
                }
            ),
            'country': CountrySelectWidget(
                attrs={
                    'class': 'form-control',
                    'id': 'select2-1'
                }
            ),
            'image': forms.FileInput(
                attrs={
                    'class': 'form-control filestyle',
                    'data-classinput': 'form-control inline',
                    'data-classbutton': 'btn btn-default'
                }
            ),
        }


class StatisticForm(forms.ModelForm):
    class Meta:
        model = Statistics
        fields = (
            'pace',
            'shooting',
            'passing',
            'dribbling',
            'defending',
            'physical',
        )

        widgets = {
            'pace': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'shooting': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'passing': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'dribbling': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'defending': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'physical': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }

apps/teams/forms.py
from django import forms
from apps.teams.models import Team, Stadium


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = (
            'name',
            'foundation',
            'image'
        )

        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': False
                }
            ),
            'image': forms.FileInput(
                attrs={
                    'class': 'form-control filestyle',
                    'data-classinput': 'form-control inline',
                    'data-classbutton': 'btn btn-default'
                }
            ),
            'foundation': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }


class StadiumForm(forms.ModelForm):
    prefix = 'stadium'

    class Meta:
        model = Stadium
        fields = (
            'name',
            'image',
            'capacity',
        )

        labels = {
            'name': 'Name',
            'image': 'Image',
            'capacity': 'Capacity',
        }

        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'image': forms.FileInput(
                attrs={
                    'class': 'form-control filestyle',
                    'data-classinput': 'form-control inline',
                    'data-classbutton': 'btn btn-default'
                }
            ),
            'capacity': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
        }

apps/players/views.py
from django.shortcuts import HttpResponseRedirect, render, HttpResponse
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.core.urlresolvers import reverse_lazy
from django.core.exceptions import ObjectDoesNotExist
from apps.players.forms import PlayerForm, StatisticForm
from apps.players.models import Player

from django.template.loader import get_template
from django.template import Context
import pdfkit

# Create your views here.


class ListPlayer(ListView):
    model = Player
    template_name = 'players/index.html'


class CreatePlayer(CreateView):
    model = Player
    form_class = PlayerForm
    template_name = 'players/create.html'
    success_url = reverse_lazy('players:list')

    def get_context_data(self, **kwargs):
        context = super(CreatePlayer, self).get_context_data(**kwargs)
        form_statistic = StatisticForm
        context['form_statistic'] = form_statistic
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        form_statistic = StatisticForm(request.POST)
        if form.is_valid() and form_statistic.is_valid():
            return self.form_valid(form, form_statistic)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, form_statistic):
        self.player = form.save()
        form_statistic.instance.player = self.player
        form_statistic.save()
        return super(CreatePlayer, self).form_valid(form)


class EditPlayer(UpdateView):
    model = Player
    form_class = PlayerForm
    template_name = 'players/edit.html'
    success_url = reverse_lazy('players:list')

    def get_context_data(self, **kwargs):
        context = super(EditPlayer, self).get_context_data(**kwargs)
        try:
            statistic = self.get_object().statistic
            form_statistic = StatisticForm(instance=statistic)
        except ObjectDoesNotExist:
            form_statistic = StatisticForm()
        context['form_statistic'] = form_statistic
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print(self.object)
        form = self.form_class(
            request.POST,
            request.FILES,
            instance=self.object
        )
        print(form)
        statistic = self.get_object().statistic
        form_statistic = StatisticForm(request.POST, instance=statistic)
        if form.is_valid() and form_statistic.is_valid():
            return self.form_valid(form, form_statistic)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, form_statistic):
        self.object = form.save()
        form_statistic.save()
        return HttpResponseRedirect(self.get_success_url())


class DeletePlayer(DeleteView):
    model = Player
    success_url = reverse_lazy('players:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


def report_player(request, pk):
    print('fdkjhjfhdlkl')
    host = request.get_host()
    print(host)
    template = get_template('reports/players/by_player.html')
    print('fdkjfn', template)
    html = template.render()
    print('fdkjfnwwwwwwwwww', html)

    pdf = pdfkit.from_string(html, 'fvl.pdf')
    response = HttpResponse(pdf, content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="ourcodeworld.pdf"'

    return response  # returns the response.

def test_report(request):

    return render(request, 'reports/players/by_player.html', {})

def send_email(request):
    pass

apps/teams/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    View
)
from django.core.urlresolvers import reverse_lazy
from django.core import serializers
from django.http import HttpResponse
from apps.teams.forms import TeamForm, StadiumForm
from apps.teams.models import Team, Stadium
from apps.players.models import Player, Statistics


from django.template.loader import get_template
from django.template import Context
import pdfkit

# Create your views here.
class ListTeams(ListView):
    model = Team
    template_name = 'teams/index.html'


class CreateTeam(CreateView):
    model = Team
    form_class = TeamForm
    template_name = 'teams/create.html'
    success_url = reverse_lazy('teams:list')

    def get_context_data(self, **kwargs):
        context = super(CreateTeam, self).get_context_data(**kwargs)
        form_stadium = StadiumForm
        context['form_stadium'] = form_stadium
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        print(form)
        form_stadium = StadiumForm(request.POST, request.FILES)
        if form.is_valid() and form_stadium.is_valid():
            return self.form_valid(form, form_stadium)
        else:
            return self.form_invalid(form, form_stadium)

    def form_valid(self, form, form_stadium):
        self.team = form.save()
        form_stadium.instance.team = self.team
        form_stadium.save()
        return super(CreateTeam, self).form_valid(form)

    def form_invalid(self, form, form_stadium):
        return self.render_to_response(self.get_context_data(form=form))


class EditTeam(UpdateView):
    modal = Team
    form_class = TeamForm
    template_name = 'teams/edit.html'
    success_url = reverse_lazy('teams:list')
    queryset = Team.objects.all()

    def get_context_data(self, **kwargs):
        context = super(EditTeam, self).get_context_data(**kwargs)
        stadium = self.get_object().team_stadium
        form_stadium = StadiumForm(
            instance=stadium,
            prefix='stadium'
        )
        context['form_stadium'] = form_stadium
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(
            request.POST,
            request.FILES,
            instance=self.object
        )
        stadium = self.get_object().team_stadium
        form_stadium = StadiumForm(
            request.POST,
            request.FILES,
            instance=stadium,
            prefix='stadium'
        )
        if form.is_valid() and form_stadium.is_valid():
            return self.form_valid(form, form_stadium)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, form_stadium):
        self.object = form.save()
        form_stadium.save()
        return HttpResponseRedirect(self.get_success_url())


class DeleteTeam(DeleteView):
    modal = Team
    success_url = reverse_lazy('teams:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class ListPlayersByTeam(View):
    template_name = 'teams/players.html'

    def get(self, request, pk):
        players = Player.objects.filter(team__pk=pk)
        team = get_object_or_404(Team, id=pk)
        data = {
            'players': players,
            'team': team,
        }
        return render(request, self.template_name, data)


class ListStadiumByTeam(View):
    template_name = 'teams/stadium.html'
    model = Stadium

    def get(self, request, pk):
        stadium = Stadium.objects.get(team__pk=pk)
        data = {
            'stadium': stadium,
        }
        return render(request, self.template_name, data)


def get_players_by_country(request):
    country = request.GET.get('country')
    team_id = request.GET.get('team_id')
    players = Player.objects.filter(country=country, team=team_id)
    json_players = serializers.serialize('json', players)
    return HttpResponse(json_players, content_type="application/json")



def get_detail_player(request):
    player_id = request.GET.get('player_id')
    statistic = Statistics.objects.get(player__pk=player_id)
    json_statistic = serializers.serialize("json", [statistic])
    # query = Statistics.objects.get(player__pk=player_id)
    # .select_related('player')

    # print('sdd', query)
    # print(serializers.serialize("json", [player.statistic, player]))

    return HttpResponse(serializers.serialize("json", [statistic]), content_type="application/json")


def report_player(request):
    pass

templates/teams/create.html
{% extends 'layouts/admin/base.html' %}

{% load staticfiles %}

{% block extra-css %}
    <link rel="stylesheet" href="{% static 'css/datetimepicker.min.css' %}">
{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/filestyle.js' %}"></script>
    <script src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'js/datetimepicker.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker({
                format: 'YYYY-MM-DD'
            });
        });
    </script>
{% endblock %}

{% block content %}
<div class="content-heading">
    <!-- START Language list-->
    <div class="pull-right">
        <a type="button" href="{% url 'teams:list' %}" class="mb-sm btn btn-success btn-outline btn-square">Back</a>
    </div>
    <!-- END Language list    -->
    New team
</div>
<div class="row">
    <div class="col-lg-12">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-body">
                <form role="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h3>Team</h3>
                    <div class="col-lg-6">
                        <div class="form-group">
                            {{ form.errors }}
                            <label>Name</label>
                            {{ form.name }}
                        </div>
                        <div class="form-group mb">
                            <label>Foundation</label>
                            <div id="datetimepicker1" class="input-group date">
                                {{ form.foundation }}
                                <span class="input-group-addon">
                                    <span class="fa fa-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        {{  form_stadium.errors}}
                        <div class="form-group">
                            <label>Name</label>
                            {{ form_stadium.name }}
                        </div>
                        <div class="form-group">
                            <label>Capacity</label>
                            {{ form_stadium.capacity }}
                        </div>
                        <div class="form-group">
                            <label>Image</label>
                            {{ form_stadium.image }}
                        </div>
                    </div>
                    <div class="pull-left">
                        <button type="submit" class="btn btn-sm btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
        <!-- END panel-->
    </div>
</div>
{% endblock %}

templates/teams/edit.html
{% extends 'layouts/admin/base.html' %}

{% load staticfiles %}

{% block extra-css %}
    <link rel="stylesheet" href="{% static 'css/datetimepicker.min.css' %}">
{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/filestyle.js' %}"></script>
    <script src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'js/datetimepicker.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker({
                format: 'YYYY-MM-DD'
            });
        });
    </script>
{% endblock %}

{% block content %}
<div class="content-heading">
    <!-- START Language list-->
    <div class="pull-right">
        <a type="button" href="{% url 'teams:list' %}" class="mb-sm btn btn-success btn-outline btn-square">Back</a>
    </div>
    <!-- END Language list    -->
    Edit team
</div>
<div class="row">
    <div class="col-lg-12">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-body">
                <form role="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h3>Team</h3>
                    <div class="col-lg-6">
                        <div class="form-group">
                            {{ form.errors }}
                            <label>{{ form.name.label }}</label>
                            {{ form.name }}
                        </div>
                        <div class="form-group">
                            {{ form.errors }}
                            <label>Image</label>
                            {{ form.image }}
                        </div>
                        <div class="form-group mb">
                            {% if form %}
                                {{ form.foundation.errors }}
                            {% endif %}
                            <label>Foundation</label>
                            <div id="datetimepicker1" class="input-group date">
                                {{ form.foundation }}
                                <span class="input-group-addon">
                                    <span class="fa fa-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        {{  form_stadium.errors}}
                        <div class="form-group">
                            <label>{{ form_stadium.name.label }}</label>
                            {{ form_stadium.name }}
                        </div>
                        <div class="form-group">
                            <label>{{ form_stadium.capacity.label }}</label>
                            {{ form_stadium.capacity }}
                        </div>
                        <div class="form-group">
                            <label>{{ form_stadium.image.label }}</label>
                            {{ form_stadium.image }}
                        </div>
                    </div>
                    <div class="pull-left">
                        <button type="submit" class="btn btn-sm btn-primary">Edit</button>
                    </div>
                </form>
            </div>
        </div>
        <!-- END panel-->
    </div>
</div>
{% endblock %}

templates/teams/index.html
{% extends 'layouts/admin/base.html' %}

{% block content %}
<h3>Page title
    <small>Subtitle</small>
</h3>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Foundation</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for team in object_list %}
                            <tr>
                                <td>{{ team.id }}</td>
                                <td>{{ team.name }}</td>
                                <td>{{ team.foundation }}</td>
                                <td>
                                    {% if team.team_stadium %}
                                    <a href="{% url 'teams:stadium' team.id %}" class="btn btn-square btn-default">Stadium</a>
                                    {% endif %}
                                    <a href="{% url 'teams:players' team.id %}" class="btn btn-square btn-default">Players</a>
                                    <a href="{% url 'teams:edit' team.id %}" class="btn btn-square btn-default">Edit</a>
                                    <a href="{% url 'teams:delete' team.id %}" class="btn btn-square btn-danger">Delete</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="">
                        <a href="{% url 'teams:create' %}" class="btn btn-square btn-primary">New Team</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/teams/players.html
{% extends 'layouts/admin/base.html' %}

{% load staticfiles %}

{% block extra-js %}
     <script src="{% static 'js/backend/teams/players.js' %}"></script>
    <!-- <script src="{% static 'js/Chart.js' %}"></script> -->
{% endblock %}

{% block content %}
<div class="content-heading">
    <!-- START Language list-->
    <div class="pull-right">
        <a type="button" href="{% url 'teams:list' %}" class="mb-sm btn btn-success btn-outline btn-square">Back</a>
    </div>
    <!-- END Language list    -->
    {{ team.name }}
    <input type="hidden" id="team_id" value="{{ team.id }}">
    <div class="form-group">
        <select class="form-control m-b" name="country" id="country">
            <option value="">------------</option>
            {% for player in players %}
            <option value="{{ player.country }}">{{ player.country.name }}</option>
            {% endfor %}
        </select>
    </div>
    <small data-localize="dashboard.WELCOME"></small>
</div>
<div class="row" id="row">
    {% for player in players %}
    <div class="col-md-4">
        <div class="panel widget">
            <div class="row row-table row-flush">
                <div class="col-xs-5">
                    <picture class="lateral-picture">
                        {% if player.image %}
                        <img src="{{ player.image.url }}" alt="">
                        {% endif %}
                    </picture>
                </div>
                <div class="col-xs-7 align-middle p-lg">
                    <div class="pull-right">
                        <a href="#" ><span class="label label-primary pull-right"><h4>{{ player.number }}</h4></span></a>
                    </div>
                    <p>
                        <h3>{{ player.name }} {{ player.lastname }}</h3>
                        <strong>{{ player.position }}</strong>
                        <p>{{ player.country.name }}</p>
                    </p>
                    <div class="pull-right">
                        <a type="button" id="{{ player.id }}" class="mb-sm btn btn-info btn-outline btn-square detail"> Detail</a>
                        <a type="button" href="{% url 'players:report_player' player.id %}" class="mb-sm dropdown-toggle btn btn-warning btn-outline btn-square detail">
                            <em class="fa fa-download"></em> Report
                        </a>
                        <a type="button" href="{% url 'players:report_player' player.id %}" class="mb-sm dropdown-toggle btn btn-success btn-outline btn-square detail">
                            <em class="fa fa-send-o"></em> Report
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}


{% block modal %}
<!-- Modal-->
<div id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" class="modal fade">
    <div class="modal-dialog">
        <!-- START panel-->
        <div id="panelDemo7" class="panel panel-default">
            <div class="panel-heading">Detail</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6"></div>
                    <div class="col-md-6">
                        <div class="panel">
                            <div class="panel-heading">Default</div>
                            <div class="panel-body text-center">
                                <div id="easypie1" data-percent="85" class="easypie-chart">
                                <span>85</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row_statistic">
                    <!-- Pace -->
                    <div class="panel-heading">Pace
                        <div class="btn-group pull-right"></div>
                    </div>
                    <div class="panel-body" id="pace"></div>
                    <!-- Shooting -->
                    <div class="panel-heading">Shooting
                        <div class="btn-group pull-right"></div>
                    </div>
                    <div class="panel-body" id="shooting"></div>
                    <!-- Passing -->
                    <div class="panel-heading">Passing
                        <div class="btn-group pull-right"></div>
                    </div>
                    <div class="panel-body" id="passing"></div>
                    <!-- Dribbling -->
                    <div class="panel-heading">Dribbling
                        <div class="btn-group pull-right"></div>
                    </div>
                    <div class="panel-body" id="dribbling"></div>
                    <!-- Defending -->
                    <div class="panel-heading">Defending
                        <div class="btn-group pull-right"></div>
                    </div>
                    <div class="panel-body" id="defending"></div>
                    <!-- Physical -->
                    <div class="panel-heading">Physical
                        <div class="btn-group pull-right"></div>
                    </div>
                    <div class="panel-body" id="physical"></div>
                </div>
                <div class="row"></div>
            </div>
        </div>
        <!-- END panel-->
    </div>
</div>`
{% endblock %}

templates/teams/team_confirm_delete.html
{% extends 'layouts/admin/base.html' %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}