admin/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    login, logout,
    password_reset, password_reset_done,
    password_reset_confirm, password_reset_complete
)
from apps.users import views

url_password_reset = {
    'template_name':'auth/password/send_email.html',
    'email_template_name':'auth/password/reset_email.html'
}
url_password_done = {
    'template_name':'auth/password/reset_done.html'
}
url_password_confirm = {
    'template_name': 'auth/password/reset_confirm.html'
}
url_done = {
    'template_name': 'auth/password/reset_complete.html'
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login, {'template_name':'auth/login.html'}, name='login'),
    url(r'^register/', views.register_user, name = 'register'),
    url(r'^logout/$', logout, {'next_page': '/'}, name= 'logout'),
    url(r'^reset/password/$', password_reset,
        url_password_reset, name='password_reset'
    ),
    url(r'^reset/password_done/$', password_reset_done,
        url_password_done, name='password_reset_done'
    ),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        url_password_confirm, name='password_reset_confirm'
    ),
    url(r'^reset/done', password_reset_complete,
        url_done, name='password_reset_complete'
    ),
    #urls admin
    url(r'^', include('apps.home.urls')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^teams/', include('apps.teams.urls', namespace='teams')),
    url(r'^players/', include('apps.players.urls', namespace='players')),
    url(r'^competitions/', include('apps.competitions.urls', namespace='competitions')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/competitions/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^index/', login_required(views.index), name = 'index'),
    url(r'^create/', login_required(views.create), name = 'create'),
    url(r'^edit/(?P<id>\w+)/$', login_required(views.edit), name = 'edit'),
    url(r'^(?P<id>\w+)/teams$', login_required(views.teams), name = 'teams'),
    # url(r'^delete/(?P<id>\w+)/$', login_required(views.delete), name = 'delete'),
]

apps/teams/urls.py
from django.conf.urls import url
from apps.teams import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^list/', login_required(views.ListTeams.as_view()), name = 'list'),
    url(r'^create/', login_required(views.CreateTeam.as_view()), name = 'create'),
    url(r'^edit/(?P<pk>\w+)/$', login_required(views.EditTeam.as_view()), name = 'edit'),
    url(r'^delete/(?P<pk>\w+)/$', login_required(views.DeleteTeam.as_view()), name = 'delete'),
    url(r'^players/(?P<pk>\w+)/$', login_required(views.ListPlayersByTeam.as_view()), name = 'players'),
    url(r'^stadium/(?P<pk>\w+)/$', login_required(views.ListStadiumByTeam.as_view()), name = 'stadium'),
    url(r'^get_players_by_country/$', views.get_players_by_country, name = 'get_players_by_country'),
    url(r'^get_detail_player/$', views.get_detail_player, name = 'get_detail_player'),
]

templates/layouts/admin/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Admin</title>
    <!-- =============== VENDOR STYLES ===============-->
    <!-- FONT AWESOME-->
    <link rel="stylesheet" href="{% static 'css/fontawesome/css/font-awesome.min.css' %}">
    <!-- SIMPLE LINE ICONS-->
    <link rel="stylesheet" href="{% static 'css/simple-line-icons/css/simple-line-icons.css' %}">
    <!-- ANIMATE.CSS-->
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <!-- WHIRL (spinners)-->
    <link rel="stylesheet" href="{% static 'css/whirl.css' %}">
    <!-- =============== PAGE VENDOR STYLES ===============-->
    {% block extra-css %}{% endblock %}
    <!-- =============== BOOTSTRAP STYLES ===============-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" id="bscss">
    <!-- =============== APP STYLES ===============-->
    <link rel="stylesheet" href="{% static 'css/app.css' %}" id="maincss">
    <link id="autoloaded-stylesheet" rel="stylesheet" href="{% static 'css/theme-e.css' %}">
</head>
<body>
    <div class="wrapper">
        <!-- top navbar-->
        <header class="topnavbar-wrapper">
            <!-- START Top Navbar-->
            <nav role="navigation" class="navbar topnavbar">
                {% include 'layouts/admin/topbar.html' %}
            </nav>
            <!-- END Top Navbar-->
        </header>
        <!-- sidebar-->
        <aside class="aside">
            <!-- START Sidebar (left)-->
            <div class="aside-inner">
                <nav data-sidebar-anyclick-close="" class="sidebar">
                    <!-- START sidebar nav-->
                    <ul class="nav">
                        {% include 'layouts/admin/navbar.html' %}
                    </ul>
                    <!-- END sidebar nav-->
                </nav>
            </div>
            <!-- END Sidebar (left)-->
        </aside>
        <!-- Main section-->
        <section>
            <!-- Page content-->
            <div class="content-wrapper">
                {% block content %}{% endblock %}
            </div>
        </section>
        <!-- Page footer-->
        <footer>
            <span>&copy; 2016 - Angle</span>
        </footer>
    </div>
    <!-- =============== VENDOR SCRIPTS ===============-->
    <!-- MODERNIZR-->
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
    <!-- JQUERY-->
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- BOOTSTRAP-->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <!-- STORAGE API-->
    <script src="{% static 'js/jquery.storageapi.js' %}"></script>
    <!-- JQUERY EASING-->
    <script src="{% static 'js/jquery.easing.js' %}"></script>
    <!-- ANIMO-->
    <script src="{% static 'js/animo.js' %}"></script>
    <!-- SLIMSCROLL-->
    <script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>
    <!-- =============== PAGE VENDOR SCRIPTS ===============-->
    {% block extra-js %}{% endblock %}
    {% block modal %}{% endblock %}
    <!-- =============== APP SCRIPTS ===============-->
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

templates/layouts/admin/navbar.html
<!-- Iterates over all sidebar items-->
<li class="nav-heading ">
    <span data-localize="sidebar.heading.HEADER">Main Navigation</span>
</li>
<li class=" ">
    <!--home-->
    <a href="{% url 'home' %}" title="Profile">
        <em class="icon-user"></em>
        <span data-localize="sidebar.nav.WIDGETS">Profile</span>
    </a>
    <!--users-->
    <a href="{% url 'users:index' %}" title="Users">
        <em class="icon-people"></em>
        <span data-localize="sidebar.nav.WIDGETS">Users</span>
    </a>
    <!--teams-->
    <a href="{% url 'teams:list' %}" title="Teams">
        <em class="icon-people"></em>
        <span data-localize="sidebar.nav.WIDGETS">Teams</span>
    </a>
    <!--players-->
    <a href="{% url 'players:list' %}" title="Players">
        <em class="icon-people"></em>
        <span data-localize="sidebar.nav.WIDGETS">Players</span>
    </a>
    <!--competitions-->
    <a href="{% url 'competitions:index' %}" title="Competitions">
        <em class="icon-people"></em>
        <span data-localize="sidebar.nav.WIDGETS">Competitions</span>
    </a>
</li>

templates/layouts/admin/topbar.html
{% load staticfiles %}
<!-- START navbar header-->
<div class="navbar-header">
    <a href="#/" class="navbar-brand">
        <div class="brand-logo">
            <img src="{% static 'img/logo.png' %}" alt="App Logo" class="img-responsive">
        </div>
        <div class="brand-logo-collapsed">
            <img src="{% static 'img/logo-single.png' %}" alt="App Logo" class="img-responsive">
        </div>
    </a>
</div>
<!-- END navbar header-->
<!-- START Nav wrapper-->
<div class="nav-wrapper">
    <!-- START Left navbar-->
    <ul class="nav navbar-nav">
        <li>
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <a href="#" data-trigger-resize="" data-toggle-state="aside-collapsed" class="hidden-xs">
                <em class="fa fa-navicon"></em>
            </a>
            <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
            <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
                <em class="fa fa-navicon"></em>
            </a>
        </li>
    </ul>
    <!-- END Left navbar-->
    <!-- START Right Navbar-->
    <ul class="nav navbar-nav navbar-right">
        <!-- START Alert menu-->
        <li class="dropdown dropdown-list">
            <a href="#" data-toggle="dropdown">
                <em class="icon-user"></em>
                <span> {{request.user.username}}</span>
            </a>
            <!-- START Dropdown menu-->
            <ul class="dropdown-menu animated flipInX">
                <li>
                    <!-- START list group-->
                    <div class="list-group">
                        <!-- list item-->
                        <a href="#" class="list-group-item">
                            <div class="media-box">
                                <div class="pull-left">
                                    <em class="fa fa-twitter fa-2x text-info"></em>
                                </div>
                                <div class="media-box-body clearfix">
                                    <p class="m0">New followers</p>
                                    <p class="m0 text-muted">
                                        <small>1 new follower</small>
                                    </p>
                                </div>
                            </div>
                        </a>
                        <!-- list item-->
                        <a href="{% url 'logout' %}" class="list-group-item">
                            <div class="media-box">
                                <div class="pull-left">
                                    <em class="fa fa-sign-out fa-2x text-danger"></em>
                                </div>
                                <div class="media-box-body clearfix">
                                    <p class="m0">Logout</p>
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- END list group-->
                </li>
            </ul>
            <!-- END Dropdown menu-->
        </li>
        <!-- END Alert menu-->
    </ul>
    <!-- END Right Navbar-->
</div>
<!-- END Nav wrapper-->