admin/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    login, logout,
    password_reset, password_reset_done,
    password_reset_confirm, password_reset_complete
)
from apps.users import views

url_password_reset = {
    'template_name':'auth/password/send_email.html',
    'email_template_name':'auth/password/reset_email.html'
}
url_password_done = {
    'template_name':'auth/password/reset_done.html'
}
url_password_confirm = {
    'template_name': 'auth/password/reset_confirm.html'
}
url_done = {
    'template_name': 'auth/password/reset_complete.html'
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login, {'template_name':'auth/login.html'}, name='login'),
    url(r'^register/', views.register_user, name = 'register'),
    url(r'^logout/$', logout, {'next_page': '/'}, name= 'logout'),
    url(r'^reset/password/$', password_reset,
        url_password_reset, name='password_reset'
    ),
    url(r'^reset/password_done/$', password_reset_done,
        url_password_done, name='password_reset_done'
    ),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        url_password_confirm, name='password_reset_confirm'
    ),
    url(r'^reset/done', password_reset_complete,
        url_done, name='password_reset_complete'
    ),
    #urls admin
    url(r'^', include('apps.home.urls')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^teams/', include('apps.teams.urls', namespace='teams')),
    url(r'^players/', include('apps.players.urls', namespace='players')),
    url(r'^competitions/', include('apps.competitions.urls', namespace='competitions')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/competitions/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^index/', login_required(views.index), name = 'index'),
    url(r'^create/', login_required(views.create), name = 'create'),
    url(r'^edit/(?P<id>\w+)/$', login_required(views.edit), name = 'edit'),
    url(r'^(?P<id>\w+)/teams$', login_required(views.teams), name = 'teams'),
    # url(r'^delete/(?P<id>\w+)/$', login_required(views.delete), name = 'delete'),
]

apps/teams/urls.py
from django.conf.urls import url
from apps.teams import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^list/', login_required(views.ListTeams.as_view()), name = 'list'),
    url(r'^create/', login_required(views.CreateTeam.as_view()), name = 'create'),
    url(r'^edit/(?P<pk>\w+)/$', login_required(views.EditTeam.as_view()), name = 'edit'),
    url(r'^delete/(?P<pk>\w+)/$', login_required(views.DeleteTeam.as_view()), name = 'delete'),
    url(r'^players/(?P<pk>\w+)/$', login_required(views.ListPlayersByTeam.as_view()), name = 'players'),
    url(r'^stadium/(?P<pk>\w+)/$', login_required(views.ListStadiumByTeam.as_view()), name = 'stadium'),
    url(r'^get_players_by_country/$', views.get_players_by_country, name = 'get_players_by_country'),
    url(r'^get_detail_player/$', views.get_detail_player, name = 'get_detail_player'),
]

apps/competitions/models.py
from django.db import models
from apps.teams.models import Team

# Create your models here.


class Competition(models.Model):
    name = models.CharField(max_length=50, default='')
    image = models.ImageField(upload_to='competition_image', blank=True)
    team = models.ManyToManyField(Team)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

apps/teams/models.py
from django.db import models
from django_countries.fields import CountryField
from geoposition.fields import GeopositionField

# Create your models here.


class Team(models.Model):
    name = models.CharField(max_length=50, default='')
    foundation = models.DateField()
    image = models.ImageField(upload_to='team_image', blank=True)
    country = CountryField(blank_label='select country', null=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Stadium(models.Model):
    name = models.CharField(max_length=50, default='')
    image = models.ImageField(upload_to='stadium_image', blank=True)
    capacity = models.IntegerField(default='')
    team = models.OneToOneField(Team, related_name='team_stadium')
    position = GeopositionField(null=True, blank=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class PointOfInterest(models.Model):
    name = models.CharField(max_length=100)
    position = GeopositionField()

apps/competitions/forms.py
from django import forms
from apps.competitions.models import Competition


class CompetitionForm(forms.ModelForm):
    class Meta:
        model = Competition
        fields = (
            'name',
            'image',
            'team',)

        labels = {
            'name': 'Name',
            'image': 'Image',
            'team': 'Teams',
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'team': forms.SelectMultiple(
                attrs={
                    'class': 'form-control',
                    'id': 'select2-3'
                }
            ),
            'image': forms.FileInput(
                attrs={
                    'class': 'form-control filestyle',
                    'data-classinput': 'form-control inline',
                    'data-classbutton': 'btn btn-default'
                }
            ),
        }

apps/teams/forms.py
from django import forms
from apps.teams.models import Team, Stadium


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = (
            'name',
            'foundation',
            'image'
        )

        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': False
                }
            ),
            'image': forms.FileInput(
                attrs={
                    'class': 'form-control filestyle',
                    'data-classinput': 'form-control inline',
                    'data-classbutton': 'btn btn-default'
                }
            ),
            'foundation': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }


class StadiumForm(forms.ModelForm):
    prefix = 'stadium'

    class Meta:
        model = Stadium
        fields = (
            'name',
            'image',
            'capacity',
        )

        labels = {
            'name': 'Name',
            'image': 'Image',
            'capacity': 'Capacity',
        }

        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'image': forms.FileInput(
                attrs={
                    'class': 'form-control filestyle',
                    'data-classinput': 'form-control inline',
                    'data-classbutton': 'btn btn-default'
                }
            ),
            'capacity': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
        }

apps/competitions/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from apps.competitions.models import Competition
from apps.competitions.forms import CompetitionForm

# Create your views here.


def index(request):
    competitions = Competition.objects.all()

    data = {
        'competitions': competitions,
    }
    return render(request, 'competitions/index.html', data)


def create(request):
    if request.method == 'POST':
        form = CompetitionForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/competitions/index')
    else:
        form = CompetitionForm()
        data = {'form': form}
        return render(request, 'competitions/create.html', data)


def teams(request, id):
    return render(request, 'competitions/teams.html', {})


def edit(request, id):
    competition = get_object_or_404(Competition, id=id)

    if request.method == 'POST':
        form = CompetitionForm(
            request.POST,
            request.FILES,
            instance=competition
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/competitions/index')
    else:
        form = CompetitionForm(instance=competition)
        data = {'form': form}
        return render(request, 'competitions/edit.html', data)

apps/teams/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    View
)
from django.core.urlresolvers import reverse_lazy
from django.core import serializers
from django.http import HttpResponse
from apps.teams.forms import TeamForm, StadiumForm
from apps.teams.models import Team, Stadium
from apps.players.models import Player, Statistics


from django.template.loader import get_template
from django.template import Context
import pdfkit

# Create your views here.
class ListTeams(ListView):
    model = Team
    template_name = 'teams/index.html'


class CreateTeam(CreateView):
    model = Team
    form_class = TeamForm
    template_name = 'teams/create.html'
    success_url = reverse_lazy('teams:list')

    def get_context_data(self, **kwargs):
        context = super(CreateTeam, self).get_context_data(**kwargs)
        form_stadium = StadiumForm
        context['form_stadium'] = form_stadium
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        print(form)
        form_stadium = StadiumForm(request.POST, request.FILES)
        if form.is_valid() and form_stadium.is_valid():
            return self.form_valid(form, form_stadium)
        else:
            return self.form_invalid(form, form_stadium)

    def form_valid(self, form, form_stadium):
        self.team = form.save()
        form_stadium.instance.team = self.team
        form_stadium.save()
        return super(CreateTeam, self).form_valid(form)

    def form_invalid(self, form, form_stadium):
        return self.render_to_response(self.get_context_data(form=form))


class EditTeam(UpdateView):
    modal = Team
    form_class = TeamForm
    template_name = 'teams/edit.html'
    success_url = reverse_lazy('teams:list')
    queryset = Team.objects.all()

    def get_context_data(self, **kwargs):
        context = super(EditTeam, self).get_context_data(**kwargs)
        stadium = self.get_object().team_stadium
        form_stadium = StadiumForm(
            instance=stadium,
            prefix='stadium'
        )
        context['form_stadium'] = form_stadium
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(
            request.POST,
            request.FILES,
            instance=self.object
        )
        stadium = self.get_object().team_stadium
        form_stadium = StadiumForm(
            request.POST,
            request.FILES,
            instance=stadium,
            prefix='stadium'
        )
        if form.is_valid() and form_stadium.is_valid():
            return self.form_valid(form, form_stadium)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, form_stadium):
        self.object = form.save()
        form_stadium.save()
        return HttpResponseRedirect(self.get_success_url())


class DeleteTeam(DeleteView):
    modal = Team
    success_url = reverse_lazy('teams:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class ListPlayersByTeam(View):
    template_name = 'teams/players.html'

    def get(self, request, pk):
        players = Player.objects.filter(team__pk=pk)
        team = get_object_or_404(Team, id=pk)
        data = {
            'players': players,
            'team': team,
        }
        return render(request, self.template_name, data)


class ListStadiumByTeam(View):
    template_name = 'teams/stadium.html'
    model = Stadium

    def get(self, request, pk):
        stadium = Stadium.objects.get(team__pk=pk)
        data = {
            'stadium': stadium,
        }
        return render(request, self.template_name, data)


def get_players_by_country(request):
    country = request.GET.get('country')
    team_id = request.GET.get('team_id')
    players = Player.objects.filter(country=country, team=team_id)
    json_players = serializers.serialize('json', players)
    return HttpResponse(json_players, content_type="application/json")



def get_detail_player(request):
    player_id = request.GET.get('player_id')
    statistic = Statistics.objects.get(player__pk=player_id)
    json_statistic = serializers.serialize("json", [statistic])
    # query = Statistics.objects.get(player__pk=player_id)
    # .select_related('player')

    # print('sdd', query)
    # print(serializers.serialize("json", [player.statistic, player]))

    return HttpResponse(serializers.serialize("json", [statistic]), content_type="application/json")


def report_player(request):
    pass

templates/competitions/create.html
{% extends 'layouts/admin/base.html' %}

{% load staticfiles %}

{% block extra-css %}
    <link rel="stylesheet" href="{% static 'css/select2.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2-bootstrap.css' %}">
{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/filestyle.js' %}"></script>
    <script src="{% static 'js/select2.js' %}"></script>
{% endblock %}

{% block content %}
<div class="content-heading">
    <!-- START Language list-->
    <div class="pull-right">
        <a type="button" href="{% url 'competitions:index' %}" class="mb-sm btn btn-success btn-outline btn-square">Back</a>
    </div>
    <!-- END Language list    -->
    New Competition
</div>
<div class="row">
    <div class="col-lg-6">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-body">
                <form role="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>{{ form.name.label }}</label>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        <label>{{ form.image.label }}</label>
                        {{ form.image }}
                    </div>
                    <div class="form-group">
                        <label>{{ form.team.label }}</label>
                        {{ form.team }}
                    </div>
                    <button type="submit" class="btn btn-sm btn-primary btn-square">Save</button>
                </form>
            </div>
        </div>
        <!-- END panel-->
    </div>
</div>
{% endblock %}

templates/competitions/edit.html
{% extends 'layouts/admin/base.html' %}

{% load staticfiles %}

{% block extra-css %}
    <link rel="stylesheet" href="{% static 'css/select2.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2-bootstrap.css' %}">
{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/filestyle.js' %}"></script>
    <script src="{% static 'js/select2.js' %}"></script>
{% endblock %}

{% block content %}
<div class="content-heading">
    <!-- START Language list-->
    <div class="pull-right">
        <a type="button" href="{% url 'competitions:index' %}" class="mb-sm btn btn-success btn-outline btn-square">Back</a>
    </div>
    <!-- END Language list    -->
    New Competition
</div>
<div class="row">
    <div class="col-lg-6">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-body">
                <form role="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>{{ form.name.label }}</label>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        <label>{{ form.image.label }}</label>
                        {{ form.image }}
                    </div>
                    <div class="form-group">
                        <label>{{ form.team.label }}</label>
                        {{ form.team }}
                    </div>
                    <button type="submit" class="btn btn-sm btn-primary btn-square">Edit</button>
                </form>
            </div>
        </div>
        <!-- END panel-->
    </div>
</div>
{% endblock %}

templates/competitions/index.html
{% extends 'layouts/admin/base.html' %}

{% block content %}
<div class="content-heading">
    <!-- START Language list-->
    <div class="pull-right">
        <!-- START button group-->
        <div class="btn-group mb-sm">
            <button type="button" data-toggle="dropdown" class="btn dropdown-toggle btn-default btn-square">Edit Competition
                <span class="caret"></span>
            </button>
            <ul role="menu" class="dropdown-menu">
                {% for competition in competitions %}
                <li><a href="{% url 'competitions:edit' competition.id %}">{{ competition.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <!-- END button group-->
        <a type="button" href="{% url 'competitions:create' %}" class="mb-sm btn btn-primary btn-outline btn-square">New Competition</a>
    </div>
    <!-- END Language list    -->
    Competitions
</div>
<div class="row">
    {% for competition in competitions %}
    <div class="col-md-2">
        <!-- START widget-->
        <div class="panel widget">
            {% if competition.image %}
            <img src="{{ competition.image.url }}" alt="Image" class="img-responsive" style="width: 100%; height: 300px">
            {% endif %}
            <div class="panel-body">
            <div class="row row-table text-center">
                <div class="col-xs-4">
                    <a href="{% url 'competitions:teams' competition.id %}" style="text-decoration: none;">
                        <p style="color: #656565">Teams</p>
                    <h3 class="m0 text-primary">{{ competition.team.count }}</h3>
                    </a>

                </div>
                <div class="col-xs-4">
                    <p>Tables</p>
                    <h3 class="m0 text-primary">1500</h3>
                </div>
                <div class="col-xs-4">
                    <p>Statistics</p>
                    <h3 class="m0 text-primary">300</h3>
                </div>
            </div>
            </div>
        </div>
        <!-- END widget-->
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/competitions/teams.html
{% extends 'layouts/admin/base.html' %}

{% block content %}
<div class="content-heading">
    <!-- START Language list-->
    <div class="pull-right">
        <a type="button" href="{% url 'competitions:index' %}" class="mb-sm btn btn-success btn-outline btn-square">Back</a>
    </div>
    <!-- END Language list    -->
    Teams
</div>
{% endblock %}