admin/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    login, logout,
    password_reset, password_reset_done,
    password_reset_confirm, password_reset_complete
)
from apps.users import views

url_password_reset = {
    'template_name':'auth/password/send_email.html',
    'email_template_name':'auth/password/reset_email.html'
}
url_password_done = {
    'template_name':'auth/password/reset_done.html'
}
url_password_confirm = {
    'template_name': 'auth/password/reset_confirm.html'
}
url_done = {
    'template_name': 'auth/password/reset_complete.html'
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login, {'template_name':'auth/login.html'}, name='login'),
    url(r'^register/', views.register_user, name = 'register'),
    url(r'^logout/$', logout, {'next_page': '/'}, name= 'logout'),
    url(r'^reset/password/$', password_reset,
        url_password_reset, name='password_reset'
    ),
    url(r'^reset/password_done/$', password_reset_done,
        url_password_done, name='password_reset_done'
    ),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        url_password_confirm, name='password_reset_confirm'
    ),
    url(r'^reset/done', password_reset_complete,
        url_done, name='password_reset_complete'
    ),
    #urls admin
    url(r'^', include('apps.home.urls')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^teams/', include('apps.teams.urls', namespace='teams')),
    url(r'^players/', include('apps.players.urls', namespace='players')),
    url(r'^competitions/', include('apps.competitions.urls', namespace='competitions')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/players/urls.py
from django.conf.urls import url
from apps.players import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^list/', login_required(views.ListPlayer.as_view()), name = 'list'),
    url(r'^create/', login_required(views.CreatePlayer.as_view()), name = 'create'),
    url(r'^edit/(?P<pk>\w+)/$', login_required(views.EditPlayer.as_view()), name = 'edit'),
    url(r'^delete/(?P<pk>\w+)/$', login_required(views.DeletePlayer.as_view()), name = 'delete'),
    url(r'^report_player/(?P<pk>\w+)/$', views.report_player, name = 'report_player'),
    url(r'^test_report/', views.test_report, name = 'test_report'),
]

apps/players/models.py
from django.db import models
from apps.teams.models import Team
from django_countries.fields import CountryField

# Create your models here.


class Player(models.Model):
    name = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    number = models.IntegerField()
    position = models.CharField(max_length=100)
    team = models.ForeignKey(
        Team,
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='player_image', blank=True)
    country = CountryField(blank_label='select country', null=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Statistics(models.Model):
    pace = models.IntegerField()
    shooting = models.IntegerField()
    passing = models.IntegerField()
    dribbling = models.IntegerField()
    defending = models.IntegerField()
    physical = models.IntegerField()
    player = models.OneToOneField(Player, related_name='statistic')

apps/players/forms.py
from django import forms
from apps.players.models import Player, Statistics
from django_countries.widgets import CountrySelectWidget


class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = (
            'name',
            'lastname',
            'number',
            'position',
            'team',
            'image',
            'country',)

        labels = {
            'name': 'Name',
            'lastname': 'Lastname',
            'number': 'Number',
            'position': 'Position',
            'team': 'Team',
            'image': 'Image',
            'country': 'Country',
        }

        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': False
                }
            ),
            'lastname': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'number': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'position': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'team': forms.Select(
                attrs={
                    'class': 'form-control'
                }
            ),
            'country': CountrySelectWidget(
                attrs={
                    'class': 'form-control',
                    'id': 'select2-1'
                }
            ),
            'image': forms.FileInput(
                attrs={
                    'class': 'form-control filestyle',
                    'data-classinput': 'form-control inline',
                    'data-classbutton': 'btn btn-default'
                }
            ),
        }


class StatisticForm(forms.ModelForm):
    class Meta:
        model = Statistics
        fields = (
            'pace',
            'shooting',
            'passing',
            'dribbling',
            'defending',
            'physical',
        )

        widgets = {
            'pace': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'shooting': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'passing': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'dribbling': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'defending': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'physical': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }

apps/players/views.py
from django.shortcuts import HttpResponseRedirect, render, HttpResponse
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.core.urlresolvers import reverse_lazy
from django.core.exceptions import ObjectDoesNotExist
from apps.players.forms import PlayerForm, StatisticForm
from apps.players.models import Player

from django.template.loader import get_template
from django.template import Context
import pdfkit

# Create your views here.


class ListPlayer(ListView):
    model = Player
    template_name = 'players/index.html'


class CreatePlayer(CreateView):
    model = Player
    form_class = PlayerForm
    template_name = 'players/create.html'
    success_url = reverse_lazy('players:list')

    def get_context_data(self, **kwargs):
        context = super(CreatePlayer, self).get_context_data(**kwargs)
        form_statistic = StatisticForm
        context['form_statistic'] = form_statistic
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        form_statistic = StatisticForm(request.POST)
        if form.is_valid() and form_statistic.is_valid():
            return self.form_valid(form, form_statistic)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, form_statistic):
        self.player = form.save()
        form_statistic.instance.player = self.player
        form_statistic.save()
        return super(CreatePlayer, self).form_valid(form)


class EditPlayer(UpdateView):
    model = Player
    form_class = PlayerForm
    template_name = 'players/edit.html'
    success_url = reverse_lazy('players:list')

    def get_context_data(self, **kwargs):
        context = super(EditPlayer, self).get_context_data(**kwargs)
        try:
            statistic = self.get_object().statistic
            form_statistic = StatisticForm(instance=statistic)
        except ObjectDoesNotExist:
            form_statistic = StatisticForm()
        context['form_statistic'] = form_statistic
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print(self.object)
        form = self.form_class(
            request.POST,
            request.FILES,
            instance=self.object
        )
        print(form)
        statistic = self.get_object().statistic
        form_statistic = StatisticForm(request.POST, instance=statistic)
        if form.is_valid() and form_statistic.is_valid():
            return self.form_valid(form, form_statistic)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, form_statistic):
        self.object = form.save()
        form_statistic.save()
        return HttpResponseRedirect(self.get_success_url())


class DeletePlayer(DeleteView):
    model = Player
    success_url = reverse_lazy('players:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


def report_player(request, pk):
    print('fdkjhjfhdlkl')
    host = request.get_host()
    print(host)
    template = get_template('reports/players/by_player.html')
    print('fdkjfn', template)
    html = template.render()
    print('fdkjfnwwwwwwwwww', html)

    pdf = pdfkit.from_string(html, 'fvl.pdf')
    response = HttpResponse(pdf, content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="ourcodeworld.pdf"'

    return response  # returns the response.

def test_report(request):

    return render(request, 'reports/players/by_player.html', {})

def send_email(request):
    pass

templates/players/create.html
{% extends 'layouts/admin/base.html' %}

{% load staticfiles %}


{% block extra-css %}
    <link rel="stylesheet" href="{% static 'css/select2.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2-bootstrap.css' %}">
{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/filestyle.js' %}"></script>
    <script src="{% static 'js/select2.js' %}"></script>
{% endblock %}

{% block content %}
<div class="content-heading">
    <!-- START Language list-->
    <div class="pull-right">
        <a type="button" href="{% url 'players:list' %}" class="mb-sm btn btn-success btn-outline btn-square">Back</a>
    </div>
    <!-- END Language list    -->
    New Player
</div>
<div class="row">
    <div class="col-lg-12">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-body">
                <form role="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Name</label>
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                <label>Lastname</label>
                                {{ form.lastname }}
                            </div>
                            <div class="form-group">
                                <label>Number</label>
                                {{ form.number }}
                            </div>
                            <div class="form-group">
                                <label>Position</label>
                                {{ form.position }}
                            </div>
                            <div class="form-group">
                                <label>Image</label>
                                {{ form.image }}
                            </div>
                            <div class="form-group">
                                <label>Teams</label>
                                {{ form.team }}
                            </div>
                            <div class="form-group">
                                <label>Country</label>
                                {{ form.country }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Pace</label>
                                {{ form_statistic.pace }}
                            </div>
                            <div class="form-group">
                                <label>shooting</label>
                                {{ form_statistic.shooting }}
                            </div>
                            <div class="form-group">
                                <label>Passing</label>
                                {{ form_statistic.passing }}
                            </div>
                            <div class="form-group">
                                <label>Dribbling</label>
                                {{ form_statistic.dribbling }}
                            </div>
                            <div class="form-group">
                                <label>Defending</label>
                                {{ form_statistic.defending }}
                            </div>
                            <div class="form-group">
                                <label>Physical</label>
                                {{ form_statistic.physical }}
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-sm btn-primary btn-square">Save</button>
                </form>
            </div>
        </div>
        <!-- END panel-->
    </div>
</div>
{% endblock %}

templates/players/edit.html
{% extends 'layouts/admin/base.html' %}

{% load staticfiles %}

{% block extra-css %}
    <link rel="stylesheet" href="{% static 'css/select2.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2-bootstrap.css' %}">
{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/filestyle.js' %}"></script>
    <script src="{% static 'js/select2.js' %}"></script>
{% endblock %}

{% block content %}
<div class="content-heading">
    <div class="pull-right">
        <a type="button" href="{% url 'players:list' %}" class="mb-sm btn btn-success btn-outline btn-square">Back</a>
    </div>
    Edit Player
</div>
<div class="row">
    <div class="col-lg-12">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-body">
                <form role="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Name</label>
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                <label>Lastname</label>
                                {{ form.lastname }}
                            </div>
                            <div class="form-group">
                                <label>Number</label>
                                {{ form.number }}
                            </div>
                            <div class="form-group">
                                <label>Position</label>
                                {{ form.position }}
                            </div>
                            <div class="form-group">
                                <label>Teams</label>
                                {{ form.team }}
                            </div>
                            <div class="form-group">
                                <label>Country</label>
                                {{ form.country }}
                            </div>
                            <div class="form-group">
                                <label>Image</label>
                                {{ form.image }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Pace</label>
                                {{ form_statistic.pace }}
                            </div>
                            <div class="form-group">
                                <label>Shooting</label>
                                {{ form_statistic.shooting }}
                            </div>
                            <div class="form-group">
                                <label>Passing</label>
                                {{ form_statistic.passing }}
                            </div>
                            <div class="form-group">
                                <label>Dribbling</label>
                                {{ form_statistic.dribbling }}
                            </div>
                            <div class="form-group">
                                <label>Defending</label>
                                {{ form_statistic.defending }}
                            </div>
                            <div class="form-group">
                                <label>Physical</label>
                                {{ form_statistic.physical }}
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-sm btn-primary btn-square">Save</button>
                </form>
            </div>
        </div>
        <!-- END panel-->
    </div>
</div>
{% endblock %}

templates/players/index.html
{% extends 'layouts/admin/base.html' %}

{% block content %}
<h3>Players
    <small>Subtitle</small>
</h3>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Lastname</th>
                                <th>Number</th>
                                <th>Country</th>
                                <th>Position</th>
                                <th>Team</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for player in object_list %}
                            <tr>
                                <td>{{ player.id }}</td>
                                <td>{{ player.name }}</td>
                                <td>{{ player.lastname }}</td>
                                <td>{{ player.number }}</td>
                                <td>{{ player.country.name }}</td>
                                <td>{{ player.position }}</td>
                                <td>{{ player.team }}</td>
                                <td>
                                    <a href="{% url 'players:edit' player.id %}" class="btn btn-square btn-default">Edit</a>
                                    <a href="{% url 'players:delete' player.id %}" class="btn btn-square btn-danger">Delete</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="">
                        <a href="{% url 'players:create' %}" class="btn btn-square btn-primary">New Player</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}